baseURL: https://francis-panzani.github.io/

copyright: Everything is mine
defaultContentLanguage: en
# languageCode: fr-FR
languageCode: en-us
title: "Francis Panzani E-porteFolio"
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    title: Francis Panzani E-porteFolio 
    weight: 1
    
  fr:
    languageName: Français
    params:
#linkedin: https://linkedin.com/fr/whoever
      navigation:
        help: Aide
        home: Acceuil
        more: Plus
        posts: posts
        publications: publications
        extracurricular_activities: autres
        view_certificate: voir_certificat
        navigation: navigation
        contact_me: me_contacter
    title: PorteFolio Numérique de Francis Panzani
    weight: 1

# Control TOC depth
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: true

# Enable global emoji support
enableEmoji: true

# Enable Google Analytics
googleAnalytics: G-L8WV0RBRYG

# Site parameters
params:
  #in asset/images
  background: "images/background_2620726.jpg"
  # GitHub repo URL of your site
  gitRepo: https://github.com/Francis-Panzani/Francis-Panzani

  # specify whether you want to write some blog posts or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false
  
    # The inverted logo will be used in the initial transparent navbar and
# the main logo will be used in the non-transparent navbar.
  logo:
    main: images/avatar_cercle.png
    inverted: images/avatar_cercle.png
    favicon: images/secnumacademie_toque.png
