baseURL: https://francis-panzani.github.io/
#voir a gerer le footer et nav fr qui pas comme le bn
languageCode: en-us
title: "Francis Panzani's E-PorteFolio"
theme: "toha"

copyright: Everything is mine

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1
  fr:
    languageName: Français
    weight: 3

# Force a locale to be use, really useful to develop the application ! Should be commented in production, the "weight" should rocks.
# DefaultContentLanguage: bn

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
    - HTML
    - RSS
    - JSON

# Enable Google Analytics
googleAnalytics: G-L8WV0RBRYG

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # Background image of the landing page
  background: /images/background_2620726.jpg

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  logo:
    main: /images/FPinv.gif
    inverted: /images/FP.gif
    favicon: /images/secnumacademie_toque.png

  # GitHub repo of your site
  gitRepo: https://github.com/Francis-Panzani/francis-panzani.github.io
  # Default branch of your Git repo
  gitBranch: source

  # Configure the number of section title visible in the top navbar
  topNavbar:
    maxVisibleSections: 5

  # Configure various features of this theme
  features:
    # Enable and configure portfolio
    portfolio:
      enable: true
    # Enable and configure blog posts
    blog:
      enable: true
      # Share post on different social media
      shareButtons:
        facebook: true
        twitter: true
        linkedin: true
        reddit: false
        whatsapp: true
        email: true
        # tumblr: true
        # pocket: true
        # diaspora: true
        # mastodon: true

    # Enable & configure "Notes" features
    notes:
      enable: false

    # Enable comment feature. There, should be only one of them.
    comment:
      enable: false
      disqus:
        shortName: toha-example-site
      # valine:
      #   appId: HTV6askWxVo3vOxlqjjaq2hd-MsYXbMMI
      #   appKey: pVrT3C85KGIuk27t07eh6bUC
      #   avatar: retro
      #   placeholder: Share your thought.
      #   lang: en
      #   recordIP: true
      #   enableQQ: true
      # utteranc:
      #   repo: github.com/hugo-toha/hugo-toha.github.io
      #   issueTerm: title
      #   theme: github-light


  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Show tags under the post title
  enableTags: true

  # If you want to use different country flag for a language, specify them here.
  # flagOverwrites:
  # - languageCode: en
  #   countryCode: us

  #Info du formulaire de contact protégé par google
  contact_form: 
    enable: true
    footer: false 
    # url: http://localhost/_test/FORMENVOIE%20MAIL/surfree/contactv1/mail.php
    url: https://copieauto.000webhostapp.com/formulaire/mail.php
#    url: http://franpan.free.fr/sendmail/contact1/mail.php
    #google recapthca ID
    data_sitekey: 6LcF6vUdAAAAAF0buCEfK2kyuTcmyl2tPp5Uhyuh


  # Provide footer configuration.
  footer:
    enable: true
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
    template: footer.html
    # Show/hide navigation in the footer. Default is "true".
    navigation:
      enable: true
      # show custom menus in the footer
      customMenus: true
    # Show/hide "Contact Me" section in the footer. Default is "true".
    contactMe:
      enable: true
    # Show/hide credentials section in the footer. Default is "true".
    credentials:
      enable: true

    # Show/hide newsletter section in the footer. Default is "true".
    # Currently, it supports "mailchimp".
    newsletter:
      enable: false
      provider: mailchimp
      mailchimpURL: https://github.us1.list-manage.com/subscribe/post?u=19de52a4603135aae97163fd8&amp;id=094a24c76e

    # Show/hide disclaimer notice in the footer. Default is "false".
    disclaimer:
      enable: false

    #active ou pas le formulaire de contact protégé par google
    contact_form:
      enable: true

